### ISSUE TITLE
Not work BBU recovery triggers

### ISSUE THREAD

**Issue by xraynor** [mykolq/zabbix_lsi_template#1]
I have BBU and not have cachevault.
And not work recovery trigger **LSI controller {#CTLID} battery state is {ITEM.LASTVALUE}** - 

`({Template LSI JSON discovery:lsi.ctl.bbustate.["{#CTLID}"].str(Optimal)}=0 and {Template LSI JSON discovery:lsi.ctl.bbustate.["{#CTLID}"].strlen()}>0) or ({Template LSI JSON discovery:lsi.ctl.cvstate.["{#CTLID}"].str(Optimal)}=0 and {Template LSI JSON discovery:lsi.ctl.cvstate.["{#CTLID}"].strlen()}>0)`

because key **lsi.ctl.cvdata.["0"]** has status **Not supported** with error **"Status" : "Failure"**
and trigger expression **lsi.ctl.cvstate.["{#CTLID}"].strlen()}>0** causes an error
**Cannot evaluate expression: "Cannot evaluate function "SERVER:lsi.ctl.cvstate.["0"].strlen()": not enough data.".**

Same errors with triggers:
LSI controller {#CTLID} battery was replaced
LSI controller {#CTLID} battery is need to be replaced

Zabbix server 4.2.3

**Comment by mykolq** [comment]
hmm, i will check it. will create more simple triggers. separately bbu and cachevault. thank you for information

**Comment by mykolq** [comment]
fixed
