### ISSUE TITLE
Case-sensetive in postprocessing JavaScript in lsi.pd.state.["{#PDID}"] key

### ISSUE THREAD

**Issue by xraynor** [mykolq/zabbix_lsi_template#2]
Trigger **LSI physical disk "{#PDID}" is "{ITEM.LASTVALUE}"** not work because case-sensetive in postprocessing JavaScript switch(value) in **lsi.pd.state.["{#PDID}"] key:**
case 'UGood':
case 'UBad':

You can also add:
case 'GHS':
value='Global Hot Spare';

case 'DHS':
value='Dedicated Hot Spare';

case 'Rbld':
value='Rebuild';

**Comment by mykolq** [comment]
Hello! Thank you, I will fix it. Strange, that I have no notification about issue by mail.

**Comment by mykolq** [comment]
fixed. thanks
