### ISSUE TITLE
Dependent item not update 

### ISSUE THREAD

**Issue by thanhtuan** [mykolq/zabbix_lsi_template#6]
Hello,
Dependent item not check after master item check, resulting in inadequate updating of status

![image](https://user-images.githubusercontent.com/43368493/81150494-2b300100-8faa-11ea-9fc1-ee7c08f042d4.png)

pls help me

**Comment by mykolq** [comment]
throttling? can you show me your master item?

**Comment by mykolq** [comment]
Can you try new version?
